# Generated by Django 3.2.16 on 2022-12-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_rooms_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='free_places',
            field=models.IntegerField(default=3),
        ),
    ]
