# Generated by Django 3.2.16 on 2022-12-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20221215_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='places',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='free_places',
            field=models.IntegerField(),
        ),
    ]
