# Generated by Django 3.2.16 on 2022-12-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0003_dormitory_busy_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormitory',
            name='busy_places',
            field=models.IntegerField(),
        ),
    ]
