# Generated by Django 3.2.16 on 2022-12-19 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0004_alter_dormitory_busy_places'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dormitory',
            name='places_in_room_count',
        ),
    ]
