# Generated by Django 3.2.16 on 2022-12-08 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_rooms_floor'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settlers',
            new_name='Students',
        ),
    ]
