# Generated by Django 3.2.16 on 2022-12-13 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0002_alter_dormitory_address'),
        ('students', '0002_rename_settlers_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='dormitory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dormitory.dormitory'),
        ),
    ]
