# Generated by Django 3.2.16 on 2022-12-14 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0002_alter_dormitory_address'),
        ('students', '0003_students_dormitory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='dormitory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.dormitory'),
        ),
    ]
